name: HubEssentials
main: de.blablubbabc.hubessentials.HubEssentials
version: 1.3
author: blablubbabc
description: Essential stuff for a hub server.
softdepend: [InSigns, TagAPI, Votifier, Multiverse-Core, My Worlds, Transporter, Multiworld]
permissions:
    hubessentials.admin:
        description: Some bypasses for admins.
        default: op
    hubessentials.keepinventory:
        description: Players with this permission will keep there inventory when otherwise it would be cleared.
        default: op
    hubessentials.pushing.block:
        description: Can't be pushed around by the pushing snowballs.
        default: false