name: HubEssentials
main: de.blablubbabc.hubessentials.HubEssentials
version: 1.0
author: blablubbabc
description: Essential stuff for a hub server.
softdepend: [InSigns, TagAPI, Votifier, Multiverse-Core, My Worlds, Transporter, Multiworld]
permissions:
    hubessentials.admin:
        description: Some bypasses for admins.
        default: op