name: HubEssentials
main: de.blablubbabc.hubessentials.HubEssentials
version: 1.1
author: blablubbabc
description: Essential stuff for a hub server.
softdepend: [InSigns, TagAPI, Votifier, Multiverse-Core, My Worlds, Transporter, Multiworld]
permissions:
    hubessentials.admin:
        description: Some bypasses for admins.
        default: op
    hubessentials.pushing.block:
        description: Can't be pushed around by the pushing snowballs.
        default: false